### PR TITLE
chore: depositLendAndSendForLockingReceiver allowance amount

### PR DESCRIPTION
**Pull request by cryptotechmaker**

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dta2w8k Med - USDO Allowance math seems incorrect](https://app.clickup.com/t/86dta2w8k)

**Review by maarcweiss — COMMENTED** [review]
Seems like this PR should not be merged? The correct commit is: 

https://github.com/Tapioca-DAO/Tapioca-bar/commit/754222a0bbf8264199ce15d054dd8a1bb70b2e44

let me know if I am missing something though

**Comment by 0xRektora** [comment]
You're right @maarcweiss

**Comment by cryptotechmaker** [comment]
It doesn't exist anymore on https://github.com/Tapioca-DAO/Tapioca-bar/blob/magnetar-refactoring-backup/contracts/usdo/modules/UsdoMarketReceiverModule.sol

**Pull request closed without merging**
