### PR TITLE
Windhustler | `marketHelper` is not whitelisted in `removeAssetReceiver` flow [`CU-86dtj93q1`]

### PR DESCRIPTION
**Pull request by 0xRektora**
fix(`UsdoMarketReceiverModule`): Validating `marketHelper` in `_validateRemoveAsset()`   [`86dtj93q1`]

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtgnhaq deadrosez | [L-01] AssetTotsDaiLeverageExecutor minAmountOut check should be done on the sDAI received instead of on the DAI received. #4](https://app.clickup.com/t/86dtgnhaq)

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtj93q1 Windhustler | marketHelper is not whitelisted in removeAssetReceiver flow #11](https://app.clickup.com/t/86dtj93q1)

**Comment by cryptotechmaker** [comment]
Reviewed

**Comment by 0xRektora** [comment]
### Merge activity

* **May 30, 8:23 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/425).

**Pull request merged**
