### PR TITLE
Multiple lzCompose messages did not verify the legality of _srcChainSender #109

### PR DESCRIPTION
**Pull request by cryptotechmaker**

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dt3u5p2 Vast Bronze Salamander - Multiple lzCompose messages did not verify the legality of _srcChainSender #109](https://app.clickup.com/t/86dt3u5p2)

**Review by maarcweiss — COMMENTED** [review]
Aren't we missing to add it in: `UsdoOptionReceiverModule.sol` too? @cryptotechmaker

**Comment by maarcweiss** [comment]
I mean the validation that has been introduced in all the other modules:

```
if (msg_.user != srcChainSender) {
            uint256 allowanceAmont = msg_.lendAmount + msg_.depositData.amount;
            _spendAllowance(msg_.user, srcChainSender, allowanceAmont);
        }
 ```
 
is different to the one actually done here:

```
  _internalTransferWithAllowance(_options.from, srcChainSender, _options.paymentTokenAmount);
 ```

**Comment by 0xRektora** [comment]
@maarcweiss `_internalTransferWithAllowance(_options.from, srcChainSender, _options.paymentTokenAmount);` is doing the same thing as 
```
if (msg_.user != srcChainSender) {
            uint256 allowanceAmont = msg_.lendAmount + msg_.depositData.amount;
            _spendAllowance(msg_.user, srcChainSender, allowanceAmont);
        }
```
the difference is it adds a transfer operation, so I think it should be fine. However I'd create a new function `_validateAllowance`, and use it in `_internalTransferWithAllowance` and replace the other if statements with this one, for the sake of consistency.

However another problem in this PR is that the allowance amount is wrong @cryptotechmaker 
The allowance should be about the asset that'll be used for the purpose of the action
example:
```
depositLendAndSendForLockingReceiver
        if (msg_.user != srcChainSender) {
            uint256 allowanceAmont = msg_.lendAmount + msg_.depositData.amount;
            _spendAllowance(msg_.user, srcChainSender, allowanceAmont);
        }
```
This should be only `msg_.lendAmount`, technically the amount 'should' be the same as `msg_.depositData.amount`, and because of that it would create a dangling allowance

Another example is 
```
lendOrRepayReceiver
           if (msg_.user != srcChainSender) {
                uint256 allowanceAmont = msg_.lendParams.depositAmount + msg_.lendParams.removeCollateralAmount;
                _spendAllowance(msg_.user, srcChainSender, allowanceAmont);
            }
```
`msg_.lendParams.removeCollateralAmount` is not USDO so it creates a dangling allowance again.

This is a case by case scenario where we have to check how many assets are pulled by `Magnetar`, for example:
`TOFT::depositLendAndSendForLockingReceiver -> MagnetarAssetXChainModule::depositYBLendSGLLockXchainTOLP -> MagnetarAssetCommonModule::_depositYBLendSGL(data.depositData, data.singularity, IYieldBox(yieldBox), data.user, data.lendAmount)` it pulls `data.lendAmount`.

Needs to make sure that this behaviour is also implemented on both `Z` and `tap token` too. Not sure if we have 

This also could create issues on the frontend. Will push a commit addressing that but wanted to get your feedbacks too @cryptotechmaker @maarcweiss

**Comment by maarcweiss** [comment]
It does look good to me know, but again in this cases with such a refactor, we need to create specific tests for it that can make sure that what we are trying to solve can in fact not happen.

**Comment by 0xRektora** [comment]
Closing instead of merging. Changes are on `magnetar-refactoring-backup`

**Pull request closed without merging**
