### PR TITLE
Big Bang debt rate is computed using an outdated total debt from the ETH market #127

### PR DESCRIPTION
**Pull request by cryptotechmaker**

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dt22m7a Skinny Wool Mallard - Big Bang debt rate is computed using an outdated total debt from the ETH market #127](https://app.clickup.com/t/86dt22m7a)

**Review by maarcweiss — COMMENTED** [review]
This seems redundant if there is already an accrual to the ETH market when it is updated? Do we really need it? It does not introduce an issue, it just seems unnecessary @0xRektora

**Comment by 0xRektora** [comment]
You're right @maarcweiss , not sure why you added that @cryptotechmaker ? You also disputed the issue https://github.com/sherlock-audit/2024-02-tapioca-judging/issues/127#issuecomment-2002150200

**Comment by 0xRektora** [comment]
Closing instead of merging. Changes are on `magnetar-refactoring`

**Pull request closed without merging**
