### PR TITLE
Use Pearlmit on TOB exerciseOption for oTAP approval  `CU-86dthzrv6`

### PR DESCRIPTION
**Pull request by 0xRektora**
patch(`UsdoOptionReceiverModule`): Clear `Pearlmit->oTap` allowance post exercise in `_exerciseAndRefund()`  [`86dthzrv6`]

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtj3vm7 Gallo(Alex) | to recheck - bin2chen - exerciseOptionsReceiver() Lack of Ownership Check for oTAP, Allowing Anyone to Use oTAPTokenID #102](https://app.clickup.com/t/86dtj3vm7)

**Comment by 0xRektora** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/427?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#427** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/427?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#426** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/426?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#425** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/425?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#424** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/424?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#423** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/423?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#422** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/422?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#421** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/421?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @0xRektora and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
Task linked: [CU-86dthzrv6 Use Pearlmit on TOB exerciseOption for oTAP approval](https://app.clickup.com/t/86dthzrv6)

**Comment by cryptotechmaker** [comment]
Reviewed

**Comment by 0xRektora** [comment]
### Merge activity

* **May 30, 8:23 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/427).

**Pull request merged**
