### PR TITLE
Leverage borrowing with stale rate can atomically create bad debt with no prior positions and no investment #79

### PR DESCRIPTION
**Pull request by cryptotechmaker**

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dt22jbf Zealous Pineapple Duck - Leverage borrowing with stale rate can atomically create bad debt with no prior positions and no investment #79](https://app.clickup.com/t/86dt22jbf)

**Review by 0xRektora — APPROVED** [review]

**Review by maarcweiss — COMMENTED** [review]
I agree with Gallos comment on introducing DOS on repays here. Couldn't we add the following on update the exchange rate, so if the rate is stale, still use it on repayments?

```diff
-   function updateExchangeRate() public returns (bool updated, uint256 rate) {
+   function updateExchangeRate(bool updateRequired) public returns (bool updated, uint256 rate) {
        (updated, rate) = oracle.get(oracleData);

        if (updated) {
            require(rate != 0, "Market: invalid rate");
            exchangeRate = rate;
            rateTimestamp = block.timestamp;
            emit LogExchangeRate(rate);
        } else {
-           require(rateTimestamp + rateValidDuration >= block.timestamp, "Market: rate too old");
+           require(!updateRequired && rateTimestamp + rateValidDuration >= block.timestamp, "Market: rate too old");
            // Return the old rate if fetching wasn't successful & rate isn't too old
            rate = exchangeRate;
        }
    }
```

**Comment by cryptotechmaker** [comment]
I did an update a while ago. Introduced the following method https://github.com/Tapioca-DAO/Tapioca-bar/blob/fix-review-merged-latest/contracts/markets/singularity/SGLBorrow.sol#L60

**Comment by 0xRektora** [comment]
Closing instead of merging. Changes are on `magnetar-refactoring-backup`

**Pull request closed without merging**
